### ISSUE TITLE
UseOnlyFilenameForScriptName option for embedded in assembly scripts 

### ISSUE THREAD

**Issue by rterekhov** [DbUp/DbUp#648] opened 2022-09-22 08:57 UTC
For scripts from file system there is an option to use just file name for script name.
It would be nice to have the same option for embedded in assembly scripts as well.

**Comment by osexpert** [comment] 2023-10-06 18:58
Seems like a duplicate of #166

**Comment by mjauernig** [comment] 2023-10-09 07:09
Closed due to duplicate of #166.

**Closed by mjauernig** 2023-10-09 07:09 UTC
Labels: enhancement, up-for-grabs
