### ISSUE TITLE
New Feature - pass sqlcmd mode variable with database name to each migration script

### ISSUE THREAD

**Issue by michalporeba** [DbUp/DbUp#338] opened 2018-05-24 13:43 UTC
I would like to be able to execute `alter database` statements as part of my migration scripts to be able to do things like: 
 * create new database files / file groups
 * be able to disconnect all existing queries before running an upgrade
 * changing database level settings 

If there was a sqlcmd mode variable passed, say named `dbname` to each script it would be possible to write scripts like this

```sql 
alter database [$(dbname)] add filegroup MyDbModFg contains memory_optimized_data
```

To read more about sqlcmd please have a look here. 
https://docs.microsoft.com/en-us/sql/relational-databases/scripting/sqlcmd-use-with-scripting-variables?view=sql-server-2017

Of course this feature would be SQL Server specific but so will be all non-ansi migration scripts. 

If you agree with this approach I'm happy to implement it

**Comment by droyad** [comment] 2018-05-24 21:34
Is this something the existing variables feature already covers? http://dbup.readthedocs.io/en/latest/more-info/variable-substitution/

You could also use the ` DB_NAME()` sql function

**Comment by michalporeba** [comment] 2018-05-25 08:07
Hi, Thanks for the quick reply. I have missed that variable substitution but it is not quite what I was hoping for. Variable substitution works but it is not standard, which means I cannot then execute the scripts outside of DbUp. using SqlCmd mode variables allows to run the scripts using standard tools like SSMS, or SqlCmd.exe 

all you have to do is add the variable definition at the top, or pass it through parameter from the command line, so my original script for testing and debugging would change to 

```sql
:setvar dbname mydb
alter database [$(dbname)] add filegroup MyDbModFg contains memory_optimized_data
```

using `DB_NAME()` could be an option, but then it forces me to use dynamic SQL which makes the code less readable, the same query would have to be something like this 

```sql
exec('alter database ' + quotename(db_name()) + ' add filegroup MyDbModFg contains memory_optimized_data')
```
so as much as that WithVariable is very helpful and will allow me to get moving for now, but I think the inclusion of a few standard sqlcmd mode variables by default would give much to the project.

**Comment by droyad** [comment] 2018-06-04 19:58
Duplicate of #123

**Closed by droyad** 2018-06-04 19:58 UTC
