### ISSUE TITLE
MySql Stored Procedure Delimiter Issue

### ISSUE THREAD

**Issue by steve-westwood** [DbUp/DbUp#281] opened 2017-10-05 11:04 UTC
It seems that **DbUp-MySql** cannot execute scripts which utilises the `DELIMITER` command needed to create Stored Procedures.
Using: 
*DbUp-MySql v4.0.0-beta0002*
Script:
>> DELIMITER $$ 
CREATE PROCEDURE new_proc (IN new_param VARCHAR(256)) 
BEGIN 
INSERT INTO tbl (cell) VALUES (new_param); 
END$$ 
DELIMITER ;

Error:
`You have an error in your SQL syntax`

Thinking it maybe be a repeat of this issue:
https://bugs.mysql.com/bug.php?id=46429

Can execute the script manually using the `MySqlScript` method:
>> 
            using (var connection = new MySqlConnection(connectionString))
            {
                MySqlScript script = new MySqlScript(connection, File.ReadAllText(filePath));
                script.Execute();
            }

**Comment by RobMalvern** [comment] 2018-01-08 15:21
In my experience the DELIMITER command only causes a problem if it's the first command in a script. So a crude workaround (that works for me) is to add some other commands to the beginning of a script, for example:
```
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


DELIMITER $$
```

**Comment by droyad** [comment] 2018-02-26 10:38
Duplicate of #169

**Closed by droyad** 2018-02-26 10:38 UTC
Labels: bug
