### ISSUE TITLE
Compatibility issue: dbup-core v 6.0.0 and dbup-sqlserver v 5.0.41

### ISSUE THREAD

**Issue by GustavFFCG** [DbUp/DbUp#805] opened 2024-10-10 11:07 UTC
Using latest (2024-10-10) published versions of dbup-core (6.0.0) and dbup-sqlserver (5.0.41) migration fails with error message

```
Upgrade failed due to an unexpected exception: System.MissingMethodException: Method not found: 'DbUp.Engine.Output.IUpgradeLog DbUp.Builder.UpgradeConfiguration.get_Log()'.
   at SqlServerExtensions.<>c__DisplayClass4_2.<SqlDatabase>b__8()
   at DbUp.Support.TableJournal.DoesTableExist(Func`1 dbCommandFactory) in /_/src/dbup-core/Support/TableJournal.cs:line 192
   at DbUp.Support.TableJournal.<GetExecutedScripts>b__23_0(Func`1 dbCommandFactory) in /_/src/dbup-core/Support/TableJournal.cs:line 63
   at DbUp.Engine.Transactions.NoTransactionStrategy.Execute[T](Func`2 actionWithResult) in /_/src/dbup-core/Engine/Transactions/NoTransactionStrategy.cs:line 29
   at DbUp.Engine.Transactions.DatabaseConnectionManager.ExecuteCommandsWithManagedConnection[T](Func`2 actionWithResult) in /_/src/dbup-core/Engine/Transactions/DatabaseConnectionManager.cs:line 142
   at DbUp.Support.TableJournal.GetExecutedScripts() in /_/src/dbup-core/Support/TableJournal.cs:line 61
   at DbUp.Engine.UpgradeEngine.GetScriptsToExecuteInsideOperation() in /_/src/dbup-core/Engine/UpgradeEngine.cs:line 136
   at DbUp.Engine.UpgradeEngine.PerformUpgrade() in /_/src/dbup-core/Engine/UpgradeEngine.cs:line 70
Method not found: 'DbUp.Engine.Output.IUpgradeLog DbUp.Builder.UpgradeConfiguration.get_Log()'.

Database migration failed!
Method not found: 'DbUp.Engine.Output.IUpgradeLog DbUp.Builder.UpgradeConfiguration.get_Log()'.

```
Workaround: downgrade dbup-core to v 5.0.87

**Comment by 0xced** [comment] 2024-10-11 16:53
I hit the same issue. You can get it to work with the pre-release version: [dbup-sqlserver 6.0.0-beta.21](https://www.nuget.org/packages/dbup-sqlserver/6.0.0-beta.21).

I found it confusing that the `dbup-core` package was released as 6.0.0 but `dbup-sqlserver` was released as pre-release (6.0.0-beta.21) only.

**Comment by francisrpereira** [comment] 2024-10-21 20:10
same problem

**Comment by lee-stevens** [comment] 2024-10-22 12:05
+1

**Comment by droyad** [comment] 2024-10-22 12:13
You do not need to reference dbup-core.

**Comment by droyad** [comment] 2024-10-22 23:30
Duplicate of #803

**Closed by droyad** 2024-10-22 23:30 UTC
Labels: bug
