### ISSUE TITLE
Firebird upgrade script with multiple commands 

### ISSUE THREAD

**Issue by petteri-laine** [DbUp/DbUp#159] opened 2016-01-26 07:23 UTC
Firebird sql upgrade script is failing if it has multiple statements.

```
/* header comment above the statments */
ALTER TABLE "MyTable" ADD "foo" int default null;
ALTER TABLE "MyTable" ADD "bar" int default null;
```

Exception points to the second statement of the script.

Script block number: 0; Error code 335544569; Message: Dynamic SQL Error
SQL error code = -104
Token unknown - line 9, column 1
ALTER
2016-01-25 16:19:02.5423 ERROR FirebirdSql.Data.FirebirdClient.FbException (0x80004005): Dynamic SQL Error
SQL error code = -104
Token unknown - line 9, column 1
ALTER ---> Dynamic SQL Error
SQL error code = -104
Token unknown - line 9, column 1
ALTER
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteNonQuery() in c:\path\NETProvider\working\NETProvider\src\FirebirdSql.Data.FirebirdClient\FirebirdClient\FbCommand.cs:line 504
   at DbUp.Support.SqlServer.SqlScriptExecutor.<>c__DisplayClass15_0.<Execute>b__1(Func`1 dbCommandFactory) in C:\projects\dbup\src\DbUp\Support\SqlServer\SqlScriptExecutor.cs:line 125
   at DbUp.Engine.Transactions.TransactionPerScriptStrategy.Execute(Action`1 action) in C:\path\dbup\src\DbUp\Engine\Transactions\TransactionPerScriptStrategy.cs:line 16
   at DbUp.Engine.Transactions.DatabaseConnectionManager.ExecuteCommandsWithManagedConnection(Action`1 action) in C:\path\dbup\src\DbUp\Engine\Transactions\DatabaseConnectionManager.cs:line 100
   at DbUp.Support.SqlServer.SqlScriptExecutor.Execute(SqlScript script, IDictionary`2 variables) in C:\path\dbup\src\DbUp\Support\SqlServer\SqlScriptExecutor.cs:line 106

**Comment by dazinator** [comment] 2016-01-26 07:49
Guessing Firebird ado.net provider (or fb itself) has an issue with doing multiple `Alter`'s within the same batch / `DbCommand`. To test that theory, you can try seperating those 2 alter statements into 2 seperate scripts. 

Also if fb permits adding multiple columns in a single alter statement then you might try that..

**Comment by dazinator** [comment] 2016-01-26 08:10
Looked into this a bit further.. 

It may be that the current way we use the ado.net fb provider will only ever support a single command per script - based on [this so](http://stackoverflow.com/questions/9080560/firebird-dotnet-batch-inserts#9112709)

It looks like we can execute commands in batches as long as we can reliably split the sql script into batches..

Has anyone actually used dbup with fb and multiple statements per script? If not i think this probably needs some attention

**Comment by petteri-laine** [comment] 2016-01-26 08:23
It seems that FirebirdConnectionManager.cs has a regular expression which is not splitting the script correctly:

    //TODO: Possible Change - this is the PostGres version
            var scriptStatements =
                Regex.Split(scriptContents, "^\\s*;\\s*$", RegexOptions.IgnoreCase | RegexOptions.Multiline)
                    .Select(x => x.Trim())
                    .Where(x => x.Length > 0)
                    .ToArray();

**Comment by RemmondSoftTechInc** [comment] 2020-04-01 20:20
Is there any chance this is going to be merged back into DbUp?  Would be very useful for my work with Firebird.  I've been using DbUp with SQL Server and MySql and it's a shame the firebird support is so limited.

**Comment by CaieA** [comment] 2023-03-02 11:16
I updated to latest nuget pkg dbup-core 5.0.10 and dbup-firebird 5.0.8
but the problem is still there:
is still not possible to have a script with multiple statements.

**Comment by Jeern** [comment] 2023-08-21 08:46
In my company we have worked with the Firebird provider for years (since 2014) and have no problem with multiline scripts.

The problem you have described is probably because you are not aware that the firebird provider requires that the ;  (semi-colon) is on a seperate line.

I.e. 

ALTER TABLE "MyTable" ADD "foo" int default null;
ALTER TABLE "MyTable" ADD "bar" int default null;

Should be

ALTER TABLE "MyTable" ADD "foo" int default null
;

ALTER TABLE "MyTable" ADD "bar" int default null
;

This is actually a feature because you can also have procedures in a script that contains ; (semi-colon) and these should not be confused with those above.

Firebird SQL does not understand SET TERM which changes the ; to something else in tools like IBEXpert. So that is not an option. 

So it works and if it is changed it will possibly break a lot of scripts. But a possible solution could be to make the it configurable if ; or some other delimiter is used to split scripts. @mjauernig  and @sungam3r  -  I Think this issue should be closed (apparently I cannot) but it might be interesting to consider an optional delimiter - which would also be interesting for the other providers. I don't know if some of them already supports that.

I would also be a good idea to document that the ; has to be on a new line (where should that be ? )

**Comment by sungam3r** [comment] 2023-08-21 13:42
> I would also be a good idea to document that the ; has to be on a new line (where should that be documented ? )

In readme in new section like `Known issues`.

**Comment by sungam3r** [comment] 2023-08-21 13:43
@Jeern PR is welcome.

**Comment by Jeern** [comment] 2023-08-22 07:40
Added this proposal #714

**Comment by Jeern** [comment] 2023-08-22 07:58
Added this PR:  https://github.com/DbUp/DbUp/pull/716 - I will close the issue

**Closed by Jeern** 2023-08-22 07:58 UTC
Labels: dbup-firebird, documentation
