### ISSUE TITLE
NullReferenceException when invalid password

### ISSUE THREAD

**Issue by jasonkingsmill-taco** [DbUp/DbUp#523] opened 2020-08-24 22:32 UTC
Using dbup-core v4.4.0 along with dbup-sqlserver v4.4.0
I'm getting a NullReferenceException being thrown when the connection string is invalid (Invalid password) instead of the previous behaviour in v4.0.0 - logging the SQL exception to the console.

![image](https://user-images.githubusercontent.com/68842390/91102719-0e305280-e6ad-11ea-8293-0c5a7a37954c.png)

`            var upgrader = DeployChanges.To
                    .SqlDatabase(connectionString)
                    .WithScriptsAndCodeEmbeddedInAssembly(scriptsAssembly, (script) =>
                    {
                        return script.StartsWith("My.Program.Migrations.Up.");
                    })
                    .LogToConsole()
                    .LogScriptOutput()
                    .JournalToSqlTable("dbup", "MigrationsJournal")
                    .Build();`

Obviously got around this by providing a correct SQL user password, however it does cause a lot of frustration setting up a new project.

**Comment by jez9999** [comment] 2020-09-01 09:40
This is actually, as far as I can tell, a NullReferenceException when there's any error with the connection at all (like an invalid host).  Obviously it should be something more appropriate to a failed connection.  Totally agree that this is a bug.

**Comment by jez9999** [comment] 2020-09-16 14:15
@AdrianJSClark I just tried this with latest DbUp master and it seems to have been fixed since the latest NuGet release.  Any chance of another NuGet release soon?  I think quite a few fixes and functionalities have been added that justify one!

**Comment by AdrianJSClark** [comment] 2020-09-16 15:19
@jez9999 you'll have to tag @droyad in for a release. Unfortunately I don't have the right permissions to publish them.

**Comment by jez9999** [comment] 2020-09-16 16:17
@droyad DbUp could do with a new release, what do you think?

**Comment by thomaslevesque** [comment] 2020-11-02 10:28
Any news on this issue? I just ran into the same problem

**Comment by antonfelich-rma** [comment] 2020-12-04 01:15
This seems to be fixed for me on 4.5

**Comment by jez9999** [comment] 2020-12-04 06:35
I can confirm too that this is fixed on 4.5, which is available on NuGet.  Interestingly, it's not listed here on Github as a release, yet.

**Comment by markashleybell** [comment] 2021-02-13 16:51
I just ran into this too; I upgraded to v4.5 of the package and it now tells me what the actual problem is (a folder was missing on my build server). 

Not sure why the releases here aren't quite up to date with the package versions, but the latest NuGet version definitely seems to fix this issue.

**Closed** 2023-08-21 10:31 UTC
Labels: bug
