### ISSUE TITLE
Postgresql - relation "schemaversions" does not exist

### ISSUE THREAD

**Issue by jackjwilliams** [DbUp/DbUp#225] opened 2016-09-28 19:50 UTC
Not sure if I'm setting something up wrong, but anytime I try to do a PerformUpgrade (after the initial one) or GetExecutedScripts, I get the following error. I can look in my database and see that the table is there, with the first three update scripts ran against it. Is there something else I am missing for Postgresql setup maybe? Do I need to set a schema?

```
Beginning database upgrade
Fetching list of already executed scripts.
Upgrade failed due to an unexpected exception:
Npgsql.NpgsqlException:
relation "schemaversions" does not exist
Severity: ERROR
Code: 42P01
   at Npgsql.NpgsqlState.<ProcessBackendResponses>d__0.MoveNext()
   at Npgsql.ForwardsOnlyDataReader.GetNextResponseObject(Boolean cleanup)
   at Npgsql.ForwardsOnlyDataReader.GetNextRowDescription()
   at Npgsql.ForwardsOnlyDataReader.NextResultInternal()
   at Npgsql.ForwardsOnlyDataReader..ctor(IEnumerable`1 dataEnumeration, CommandBehavior behavior, NpgsqlCommand command, NotificationThreadBlock threadBlock, Boolean preparedStatement, NpgsqlRowDescription rowDescription)
   at Npgsql.NpgsqlCommand.GetReader(CommandBehavior cb)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior cb)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at DbUp.Support.Postgresql.PostgresqlTableJournal.<>c__DisplayClass7_0.<GetExecutedScripts>b__0(Func`1 dbCommandFactory) in C:\projects\dbup\src\DbUp\Support\Postgresql\PostgresqlTableJournal.cs:line 74
   at DbUp.Engine.Transactions.NoTransactionStrategy.Execute(Action`1 action) in C:\projects\dbup\src\DbUp\Engine\Transactions\NoTransactionStrategy.cs:line 14
   at DbUp.Engine.Transactions.DatabaseConnectionManager.ExecuteCommandsWithManagedConnection(Action`1 action) in C:\projects\dbup\src\DbUp\Engine\Transactions\DatabaseConnectionManager.cs:line 100
   at DbUp.Support.Postgresql.PostgresqlTableJournal.GetExecutedScripts() in C:\projects\dbup\src\DbUp\Support\Postgresql\PostgresqlTableJournal.cs:line 67
   at DbUp.Engine.UpgradeEngine.GetScriptsToExecuteInsideOperation() in C:\projects\dbup\src\DbUp\Engine\UpgradeEngine.cs:line 105
   at DbUp.Engine.UpgradeEngine.PerformUpgrade() in C:\projects\dbup\src\DbUp\Engine\UpgradeEngine.cs:line 57
Npgsql.NpgsqlException:
relation "schemaversions" does not exist
Severity: ERROR
Code: 42P01
   at Npgsql.NpgsqlState.<ProcessBackendResponses>d__0.MoveNext()
   at Npgsql.ForwardsOnlyDataReader.GetNextResponseObject(Boolean cleanup)
   at Npgsql.ForwardsOnlyDataReader.GetNextRowDescription()
   at Npgsql.ForwardsOnlyDataReader.NextResultInternal()
   at Npgsql.ForwardsOnlyDataReader..ctor(IEnumerable`1 dataEnumeration, CommandBehavior behavior, NpgsqlCommand command, NotificationThreadBlock threadBlock, Boolean preparedStatement, NpgsqlRowDescription rowDescription)
   at Npgsql.NpgsqlCommand.GetReader(CommandBehavior cb)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior cb)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at DbUp.Support.Postgresql.PostgresqlTableJournal.<>c__DisplayClass7_0.<GetExecutedScripts>b__0(Func`1 dbCommandFactory) in C:\projects\dbup\src\DbUp\Support\Postgresql\PostgresqlTableJournal.cs:line 74
   at DbUp.Engine.Transactions.NoTransactionStrategy.Execute(Action`1 action) in C:\projects\dbup\src\DbUp\Engine\Transactions\NoTransactionStrategy.cs:line 14
   at DbUp.Engine.Transactions.DatabaseConnectionManager.ExecuteCommandsWithManagedConnection(Action`1 action) in C:\projects\dbup\src\DbUp\Engine\Transactions\DatabaseConnectionManager.cs:line 100
   at DbUp.Support.Postgresql.PostgresqlTableJournal.GetExecutedScripts() in C:\projects\dbup\src\DbUp\Support\Postgresql\PostgresqlTableJournal.cs:line 67
   at DbUp.Engine.UpgradeEngine.GetScriptsToExecuteInsideOperation() in C:\projects\dbup\src\DbUp\Engine\UpgradeEngine.cs:line 105
   at DbUp.Engine.UpgradeEngine.PerformUpgrade() in C:\projects\dbup\src\DbUp\Engine\UpgradeEngine.cs:line 57
```

**Comment by DTTerastar** [comment] 2017-12-12 14:05
I'm getting this as well.  Using public schema works tho.

**Comment by DTTerastar** [comment] 2017-12-12 14:37
This happens because the code searches all schemas for that table to detect if it already exists if no schema has been specified.  The fix is to specify a schema.  This is not easy because there is no extension to configure it for you so you have to do it like this:

```                
var bldr = DeployChanges.To
          .PostgresqlDatabase(_connstring)
          .WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly(), s => s.StartsWith(location));

bldr.Configure(c => c.Journal = new PostgresqlTableJournal(() => c.ConnectionManager, () => c.Log, _schema, "schemaversions"));

var upgrader = bldr.Build();
```

**Comment by droyad** [comment] 2018-02-26 11:42
Duplicate of #197

**Closed by droyad** 2018-02-26 11:42 UTC

**Comment by rudym** [comment] 2022-04-01 01:37
had this problem due to losing permissions on the schema for `schemaversions` table
