### ISSUE TITLE
FileSystemScriptProvider Support for Folder Recursion

### ISSUE THREAD

**Issue by hrc3** [DbUp/DbUp#124] opened 2015-09-11 08:15 UTC
## Story

As a DbUp User, I would like to be able to use upgrade scripts from the file system in a multi-level folder structure in order to facilitate better organization of the upgrade scripts.
## Explanation

When upgrade scripts are included in the DbUp project as internal resources, the Scripts folder can contain multiple levels of sub-folders to help organize the upgrade scripts. However, when upgrade scripts are provided from a file system folder that does not contain scripts marked as resources, all the scripts must be in the root of the specified folder. Any sub-folders will be ignored.

The path to the file relative to the specified starting point should be used as the "manifest name" for the script. This means that sub-folder names will be significant in the ordering of scripts for processing.

**Comment by rickculpepper** [comment] 2015-09-15 09:42
@JakeGinnivan please mark as an enhancement for 4.0 and assign to me

**Comment by rintje** [comment] 2015-10-27 08:32
Would love to see this enhancement too. 
Its just what we are missing to implement dbup with our db script folder layout.

**Comment by cmarrades** [comment] 2015-11-16 13:37
I just found out if I split the scripts in multiple folders, it won't execute them ordered by script name. Not sure how it works, but I think this story would help to solve my problem as well.

**Comment by droyad** [comment] 2018-02-26 23:10
This is now supported

**Closed by droyad** 2018-02-26 23:10 UTC
Labels: enhancement

**Comment by cmarrades** [comment] 2018-02-27 09:20
better late than never :P 

Thx

**Comment by InvincibleDRT** [comment] 2018-02-28 21:37
with the new version i am getting the following error "SqlConnection does not support parallel transactions"
My code works fine with 3.3.5 build

**Comment by droyad** [comment] 2018-03-01 10:52
@InvincibleDRT Could you share your DbUp builder code as well a the stack trace for that error?

**Comment by InvincibleDRT** [comment] 2018-03-06 15:57
string branchDBInfo = string.Format(ConfigurationManager.AppSettings[keyConn], branchInfo);
            EnsureDatabase.For.SqlDatabase(branchDBInfo);

            FileSystemScriptOptions fsso = new FileSystemScriptOptions();
            fsso.IncludeSubDirectories = true;
            var upgradeBuilder = DeployChanges.To
                                    .SqlDatabase(branchDBInfo)
                                    .WithScriptsFromFileSystem(path, fsso)
                                    .WithVariablesDisabled().LogTo(this);


            upgradeBuilder.Configure(x => x.ScriptExecutor.ExecutionTimeoutSeconds = 60 * 60);
            var upgrader = upgradeBuilder.WithTransactionPerScript().Build();

            var result = upgrader.PerformUpgrade();

            object message = (result.Successful) ? "Success" : (object)result.Error;
            AddToLog(message.ToString());



I switched back to "4.0.0-beta0003" version and that works as well.

This is being called in parallel multiple threads (around 10 of them at any point of time)

**Comment by droyad** [comment] 2018-03-06 22:36
@InvincibleDRT Just to make sure I got it:
- Problem was seen on beta0004
- It works on beta0003
- The above code is called with different values for `branchInfo` in parallel in order to update multiple databases at a time

**Comment by InvincibleDRT** [comment] 2018-03-06 22:51
yes for first two points.
For the third point, it is the same database that is getting called (branchDbinfo is the same) only the path parameter changes in every thread's call. 

I will switch back to beta0004 in a bit post the stack trace

**Comment by droyad** [comment] 2018-03-06 22:56
Ah right, so you are running the scripts in parallel against the same database. So potentially the problem is in writing to the Schema Versions table.

**Comment by InvincibleDRT** [comment] 2018-03-06 22:58
hmm...I think "var upgrader = upgradeBuilder.WithTransactionPerScript().Build();" this is also coming issues. I tried removing this and it looks like its going on fine now...still a couple of thousand files to go through but started fine

**Comment by InvincibleDRT** [comment] 2018-03-06 22:59
The exact thread count at peak is 30 fyi

**Comment by InvincibleDRT** [comment] 2018-03-06 23:05
and can you please tell me if there is anyway to get what file failed, without parsing the custom logger's writeinformation method?
