### ISSUE TITLE
issue with special characters

### ISSUE THREAD

**Issue by keren-steinberg** [DbUp/DbUp#723] opened 2023-08-23 11:16 UTC
when running a script with the below, it fails

Script:
use my_schema;

/*!40000 ALTER TABLE test DISABLE KEYS /;
INSERT INTO test VALUES (1383,'aaa\\'s ')
;
INSERT INTO test VALUES (1409,'xxx;')
;
/!40000 ALTER TABLE test ENABLE KEYS */;

Error:
ERROR Script block number: 3; MySql error code: 0; Number 1064; Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''xxx' at line 2
Script block number: 3; MySql error code: 0; Number 1064; Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''xxx' at line 2
2023-08-23 12:00:25.4021 ERROR MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''xxx' at line 2
at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
at DbUp.Support.ScriptExecutor.ExecuteAndLogOutput(IDbCommand command) in //src/dbup-core/Support/ScriptExecutor.cs:line 178
at DbUp.MySql.MySqlScriptExecutor.ExecuteCommandsWithinExceptionHandler(Int32 index, SqlScript script, Action executeCommand) in //src/dbup-mysql/MySqlScriptExecutor.cs:line 40

**Comment by keren-steinberg** [comment] 2023-08-23 11:17
this is some kind of relation between the quoted "\\'" and the ";"

**Comment by keren-steinberg** [comment] 2023-08-23 11:48
This is running in mySQL DB

**Comment by mjauernig** [comment] 2023-08-25 08:26
Duplicate of #722.

**Closed by mjauernig** 2023-08-25 08:26 UTC
Labels: bug
