### ISSUE TITLE
EnsureDatabaseExists fails to create database when using postgres

### ISSUE THREAD

**Issue by ptmclean** [DbUp/DbUp#626] opened 2022-05-10 02:42 UTC
With version 4.6.0 of `dbup-postgresql` it looks as though `EnsureDatabaseExists` no longer is able to create a new database. The behaviour appears to have changed to throw an exception when the database does not exist. I assume this is not a deliberate change. 

To help demonstrate the issue I've created a repository with a minimal reproduction of the issue...
https://github.com/ptmclean/dbup-postgres-ensure-db

In essence when a call is made to `EnsureDatabase.For.PostgresqlDatabase(connectionString);` and the `Database` property on the connection string points to a non-existing database the following error is thrown...
`Npgsql.PostgresException (0x80004005): 3D000: database "<DATABASE NAME>" does not exist`

Looking back at recent commits [this](https://github.com/DbUp/DbUp/pull/605/files) looks a possible cause. Happy to create a PR to revert but wanted to check for a steer first.

**Comment by droyad** [comment] 2022-05-10 03:36
Duplicate of #619

**Closed by droyad** 2022-05-10 03:36 UTC
Labels: bug
