### ISSUE TITLE
DbUp with Username/Password Authentication Does Not Match Permission Level Of SQLCMD

### ISSUE THREAD

**Issue by bgottfried91** [DbUp/DbUp#341] opened 2018-06-20 17:47 UTC
DbUp Version=4.1.0
DotNet Framework= DotNet Core 2.1
OS = Debian 9
MSSQL Server = Microsoft SQL Server 2017 (RTM-CU5) (KB4092643) - 14.0.3023.8 (X64) Express Edition*
*deployed via [this helm chart](https://github.com/kubernetes/charts/tree/master/stable/mssql-linux)

DbUp with a connection string that uses the Username/Password authentication (sa account) does not appear to authenticate properly. Running a DbUp project with a single script that just attempts to run the command
```sql
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'cti_cisco_ctiserver')
BEGIN
	EXEC('CREATE SCHEMA cti_cisco_ctiserver')
END
```
results in 
```bash
Master ConnectionString => Data Source=100.66.61.87;Initial Catalog=master;User ID=sa;Password=********************
Beginning database upgrade
Checking whether journal table exists..
Journal table does not exist
Executing Database Server script 'Mattersight.TI.Cisco.CtiServer.Databases.Scripts.0000-UpgradeScript.sql'
Checking whether journal table exists..
Creating the [cti_cisco_ctiserver].[SchemaVersion] table
DB exception has occured in script: 'Mattersight.TI.Cisco.CtiServer.Databases.Scripts.0000-UpgradeScript.sql'
Script block number: -1; Message: The specified schema name "cti_cisco_ctiserver" either does not exist or you do not have permission to use it.
System.Data.SqlClient.SqlException (0x80131904): The specified schema name "cti_cisco_ctiserver" either does not exist or you do not have permission to use it.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& da
taReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DbUp.Support.TableJournal.EnsureTableExistsAndIsLatestVersion(Func`1 dbCommandFactory)
   at DbUp.Support.ScriptExecutor.<>c__DisplayClass18_0.<Execute>b__0(Func`1 dbCommandFactory)
   at DbUp.Support.ScriptExecutor.Execute(SqlScript script, IDictionary`2 variables)
ClientConnectionId:9136d0ca-5270-4b52-ab9c-89bfa0674e59
Error Number:2760,State:1,Class:16
Upgrade failed due to an unexpected exception:
System.Data.SqlClient.SqlException (0x80131904): The specified schema name "cti_cisco_ctiserver" either does not exist or you do not have permission to use it.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& da
taReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DbUp.Support.TableJournal.EnsureTableExistsAndIsLatestVersion(Func`1 dbCommandFactory)
   at DbUp.Support.ScriptExecutor.<>c__DisplayClass18_0.<Execute>b__0(Func`1 dbCommandFactory)
   at DbUp.Support.ScriptExecutor.Execute(SqlScript script, IDictionary`2 variables)
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()
ClientConnectionId:9136d0ca-5270-4b52-ab9c-89bfa0674e59
Error Number:2760,State:1,Class:16
System.Data.SqlClient.SqlException (0x80131904): The specified schema name "cti_cisco_ctiserver" either does not exist or you do not have permission to use it.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& da
taReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DbUp.Support.TableJournal.EnsureTableExistsAndIsLatestVersion(Func`1 dbCommandFactory)
   at DbUp.Support.ScriptExecutor.<>c__DisplayClass18_0.<Execute>b__0(Func`1 dbCommandFactory)
   at DbUp.Support.ScriptExecutor.Execute(SqlScript script, IDictionary`2 variables)
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()
ClientConnectionId:9136d0ca-5270-4b52-ab9c-89bfa0674e59
Error Number:2760,State:1,Class:16
```

Running the same command via SQLCMD using the same username/password to authenticate will successfully create the schema.

**Comment by droyad** [comment] 2018-06-20 21:35
Duplicate of #234

**Closed by droyad** 2018-06-20 21:35 UTC
