### ISSUE TITLE
Variable substitution conflicts with PostgreSQL dollar-quoted strings

### ISSUE THREAD

**Issue by AnthonyMastrean** [DbUp/DbUp#484] opened 2020-02-03 21:59 UTC
So, [dollar-quoted strings](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING) are a pretty common PostgreSQL thing. They're even part of the magic that makes [functions](https://www.postgresql.org/docs/current/sql-createfunction.html) work and are often nested, requiring the use of "tagged" quoted strings.

```
$function$
BEGIN
    RETURN ($1 ~ $q$[\t\r\n\v\\]$q$);
END;
$function$
```

If I need variable substitution in a PostgreSQL database project and have nested dollar-quoted strings, I can't just turn it off (see #288).

**Comment by Kharos** [comment] 2020-02-04 07:12
We hit the same problem. As a workaround, put the following entry in your variable dictionary:
`{ "function", "$function$" }`
This will cause dbup's variable substitution to replace `$function$` with itself.

**Comment by AnthonyMastrean** [comment] 2020-02-05 01:31
@Kharos hm, good tip, but I hope we can get a more robust fix 😅

**Comment by peterneave** [comment] 2020-02-18 04:52
Duplicate of https://github.com/DbUp/DbUp/issues/484

**Closed** 2020-02-21 07:13 UTC
Labels: bug
