### ISSUE TITLE
"Invalid Option" message when script filename has a comma (VS2015)

### ISSUE THREAD

**Issue by lonevvolf** [DbUp/DbUp#98] opened 2015-07-21 11:21 UTC
Strangely, we only have this problem in VS2015.  If the SQL script filename has a comma in it, and you are using WithScriptsEmbeddedInAssembly(), you get the error:
Invalid option '<classname>'; Resource visibility must be either 'public' or 'private'

**Comment by AdrianJSClark** [comment] 2015-07-21 14:11
This issue is, unfortunately, not caused by DbUp. It is an underlying compiler/build issue that can be reproduced within a bare Class Library assembly that does not contain DbUp. Simply include a ".txt" file with a comma in the filename marked as "Embedded Resource" and the error will be produced.

In case you're interested, the following information is what I was able to discover with a co-worker earlier today.

Something has changed between the release candidate and final release of the Roslyn C# compiler to introduce this bug. When a file is marked as "Embedded Resource" it is included as an argument a call to "csc.exe" by the msbuild scripts. The argument is the ["/resource" switch](https://msdn.microsoft.com/en-us/library/c0tyye07(v=vs.120).aspx) that includes three comma-separated elements. Normally quoting each element should allow them to contain a comma. While the command line the msbuild scripts generate is quoted correctly, at some point that quoting is ignored or stripped out.

Unfortunately our efforts to trace through the [Roslyn source code](https://github.com/dotnet/roslyn) for the root cause were unsuccessful. In the mean time, the only work-around is to ensure you do not use commas as part of your scripts when using the "Embedded Resource" build type.

**Comment by AdrianJSClark** [comment] 2015-07-21 23:12
If you are interested in tracking this problem the issue in the Roslyn GitHub project is [Issue 4021](https://github.com/dotnet/roslyn/issues/4021)

**Closed by AdrianJSClark** 2015-07-21 23:12 UTC
